In [13]:
pwd

'C:\\Users\\HP'

In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [9]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [11]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [12]:
train_labels

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

In [15]:
test_labels

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [16]:
#for x in range(len ((test_labels[0])) if x==0]
length = len([x for x in test_labels.reshape(10000) if x==0])
print(test_labels[0])
print(length)
#test_labels.shape
#test_labels.reshape(100000)

ValueError: cannot reshape array of size 100000 into shape (10000,)

In [65]:
count0=0
count1=0
count2=0
count3=0
count4=0
count5=0
count6=0
count7=0
count8=0
count9=0

for label in test_labels:
    if label[0] ==1:
        count0+=1
    elif label[1] ==1:
    
    if label[0] ==1:
        count1+=1
    elif label[2] ==1:
            
    if label[0] ==1:
        count2+=1
    elif label[3] ==1:
            
    if label[0] ==1:
        count3+=1
    elif label[4] ==1:
            
    if label[0] ==1:
        count4+=1
    elif label[5] ==1:
            
    if label[0] ==1:
        count5+=1
    elif label[6] ==1:
            
    if label[0] ==1:
        count6+=1
    elif label[7] ==1:
            
    if label[0] ==1:
        count7+=1
    elif label[8] ==1:
            
        if label[0] ==1:
            count8+=1
        elif label[9] ==1:
print(count0,+count2+count3+count4+count5+count6+count7+count8, count9)

IndentationError: expected an indented block (<ipython-input-65-22a47e2e0d5a>, line 17)

In [70]:
from collections import Counter
Counter(['train_labels','test_labels'])
#Counter({'train_labels': 3, 'test_labels': 2, 'pear': 1})

Counter({'test_labels': 1, 'train_labels': 1})

In [28]:
# len([p for p in PeopleList if p.Gender == 'F'])


NameError: name 'PeopleList' is not defined

In [17]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 10s 170us/step - loss: 0.2579 - acc: 0.9253
Epoch 2/5
60000/60000 [==============================] - 8s 127us/step - loss: 0.1050 - acc: 0.9685
Epoch 3/5
60000/60000 [==============================] - 8s 138us/step - loss: 0.0680 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 8s 126us/step - loss: 0.0497 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 8s 130us/step - loss: 0.0384 - acc: 0.9885


In [18]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 94us/step
test_acc: 0.9771
